on:
  repository_dispatch:
    types: [reliza-build-event]

name: Hello World on Trigger 2025

jobs:
  build:
    name: Build And Push
    runs-on: ubuntu-latest
    steps:
      - id: reliza-build-start 
        name: Hello World
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo "hello-world $MESSAGE"
